dist: precise
sudo: false
language: java
jdk:
  - openjdk11
  - oraclejdk8
env:
  - CAMUNDA=LATEST
  - CAMUNDA=7.15.0
  - CAMUNDA=7.14.0
  - CAMUNDA=7.13.0
  - CAMUNDA=7.12.0
  - CAMUNDA=7.11.0
  - CAMUNDA=7.10.0
  - CAMUNDA=7.9.0
  - CAMUNDA=7.8.0
  - CAMUNDA=7.7.0
  - CAMUNDA=7.6.0
  - CAMUNDA=7.5.0
  - CAMUNDA=7.4.0
  - CAMUNDA=7.3.0
  - CAMUNDA=7.2.0
  - CAMUNDA=7.1.0-Final
  - CAMUNDA=7.0.0-Final
jobs:
  exclude:
    - jdk: openjdk11
      env: CAMUNDA=7.9.0
    - jdk: openjdk11
      env: CAMUNDA=7.8.0
    - jdk: openjdk11
      env: CAMUNDA=7.7.0
    - jdk: openjdk11
      env: CAMUNDA=7.6.0
    - jdk: openjdk11
      env: CAMUNDA=7.5.0
    - jdk: openjdk11
      env: CAMUNDA=7.4.0
    - jdk: openjdk11
      env: CAMUNDA=7.3.0
    - jdk: openjdk11
      env: CAMUNDA=7.2.0
    - jdk: openjdk11
      env: CAMUNDA=7.1.0-Final
    - jdk: openjdk11
      env: CAMUNDA=7.0.0-Final
install: true
script: mvn -Dcamunda-platform-version=$CAMUNDA
